services:
  mysql:
    image: 'mysql:latest'
    hostname: mysql
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 2s
      timeout: 2s
      retries: 10

  keycloak:
    image: quay.io/keycloak/keycloak:22.0
    container_name: keycloak-service
    environment:
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://mysql:3306/mydatabase
      KC_DB_USERNAME: myuser
      KC_DB_PASSWORD: secret
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: true
      KC_HTTP_PORT: 9060
    command: [ "start-dev" ] #  export [--dir|--file] <path> --realm my-realm to export
#    volumes:
#      - ./config/keycloak-realm.json:/opt/keycloak/data/import/keycloak-realm.json
    ports:
      - "9060:9060"
    depends_on:
      mysql:
        condition: service_healthy
    hostname: keycloak
    healthcheck:
      test: [ "CMD", "curl", "-v", "http://keycloak:9060/health/ready" ]
      interval: 30s
      timeout: 10s
      retries: 10
