server:
  port: 9080

spring:
  docker:
    compose:
      file: docker-compose.yaml
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog.xml
    enabled: true

springdoc:
  model-converters:
    pageable-converter:
      enabled: 'true'
  swagger-ui:
    path: /swagger-ui
  default-produces-media-type: application/json
